## Techniques in these functions were taken from the example functions included in the instructions for this assignment.
## Using these functions may be more computationally efficient when operating on data sets requires repeated use of the inverse of a matrix.  

## This function caches a list of objects, including the inverse of a matrix.
## Since we are supplied with a matrix (and not creating one) the calling function coerces the matrix to an array.
## This keeps attributes of the matrix intact. 

makeCacheMatrix <- function(x = as.array()) {
        s <- NULL
        set <- function(y) {
                x <<- y
                s <<- NULL
        }
        get <- function() x
        setMatInv <- function(solve) s <<- 
                solve 
        getMatInv <- function() s
        list(set = set, get = get,
             setMatInv = setMatInv,
             getMatInv = getMatInv)
}


## This function retrieves the inverse array (or "matrix") generated by makeCacheMatrix() if the inverse has already been calculated.
## If the inverse has not been calculated, the function retrieves the original array (coerced matrix) from makeCacheMatrix() and returns the inverse.

cacheSolve <- function(x, ...) {
        s <- x$getMatInv()
        if(!is.null(s)) {
                return(s)
        }
        data1 <- x$get()
        s <- solve(data1, ...)
        x$setMatInv(s)
        s
}
